FROM nginx:alpine AS final

COPY ./source.tar.gz /tmp/source.tar.gz
COPY ./nginx.conf /etc/nginx/nginx.conf

RUN tar xzvf /tmp/source.tar.gz -C /usr/share/nginx/html --strip-components 1 && \
    rm /tmp/source.tar.gz /usr/share/nginx/html/50x.html

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]