apiVersion: apps/v1
kind: Deployment
metadata:
  name: aliviation-deploy
  labels:
    app: aliviation-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aliviation-deploy
  template:
    metadata:
      labels:
        app: aliviation-deploy
    spec:
      containers:
      - name: aliviation-deploy
        image: 271122/ali.viation
        ports:
        - containerPort: 80

---

# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: aliviation-service
  labels:
    app: aliviation-service
spec:
  type: ClusterIP
  selector:
    app: aliviation-deploy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
